### ISSUE TITLE
Can I use the kcorrect package to calculate z_max?

### ISSUE THREAD

**Issue by Abrygzy** [blanton144/kcorrect#6]
Dear Professor Blanton:

I am using the kcorrect package to calculate the absolute magnitudes for SDSS galaxies, which is really convenient. I also need to do V-max weighting for the galaxy sample, so I want to use this package to calculate z_max, the maximum redshift that one galaxy can observe. According to my understanding, I can achieve this by putting galaxies to the flux limit.
Here is my approach:
```python
kc = kcorrect.kcorrect.KcorrectSDSS();
# Calculate the kcorrect coefficients
coeffs = kc.fit_coeffs_asinh(redshift = gal_zs, mag=sdss_mags, mag_err=sdss_mag_errs, extinction=sdss_exts)
# Convert mags into maggies
(maggies,ivars) = kcorrect.utils.sdss_asinh_to_maggies(mag=sdss_mags, mag_err=sdss_mag_errs,extinction=sdss_exts)
# Calculate absolute magnitudes
ab_mags = kc.absmag(maggies=maggies, ivar=ivars, redshift=gal_zs, coeffs=coeffs)
ab_mags_r = ab_mags[:,2]
m_max_r = 17.77 # Flux limit
def minimize_zmax(z):
    return m_max_r - cosmo.distmod(z).value - kc.kcorrect(redshift=z, coeffs=coeff)[2] - ab_mag_r
```
Then I can get z_max where minimize_zmax(z_max) = 0 for each galaxy.
Can I get an approximate z_max in this way? Is the evolution correction (or E-correction) included in the kcorrect package?

Thanks
Abry

**Comment by blanton144** [comment]
Dear Abry,

This *looks* right to me, though of course there might be a bug I'm not
seeing.

But it does ignore the evolution correction, yes. kcorrect does not include
that ... it is a rather model dependent thing.

Thanks,
Mike

On Sat, Oct 21, 2023 at 4:27 AM Abry ***@***.***> wrote:

> Dear Professor Blanton:
>
> I am using the kcorrect package to calculate the absolute magnitudes for
> SDSS galaxies, which is really convenient. I also need to do V-max
> weighting for the galaxy sample, so I want to use this package to calculate
> z_max, the maximum redshift that one galaxy can observe. According to my
> understanding, I can achieve this by putting galaxies to the flux limit.
> Here is my approach:
>
> kc = kcorrect.kcorrect.KcorrectSDSS();# Calculate the kcorrect coefficientscoeffs = kc.fit_coeffs_asinh(redshift = gal_zs, mag=sdss_mags, mag_err=sdss_mag_errs, extinction=sdss_exts)# Convert mags into maggies
> (maggies,ivars) = kcorrect.utils.sdss_asinh_to_maggies(mag=sdss_mags, mag_err=sdss_mag_errs,extinction=sdss_exts)# Calculate absolute magnitudesab_mags = kc.absmag(maggies=maggies, ivar=ivars, redshift=gal_zs, coeffs=coeffs)ab_mags_r = ab_mags[:,2]m_max_r = 17.77 # Flux limitdef minimize_zmax(z):
>     return m_max_r - cosmo.distmod(z).value - kc.kcorrect(redshift=z, coeffs=coeff)[2] - ab_mag_r
>
> Then I can get z_max where minimize_zmax(z_max) = 0 for each galaxy.
> Can I get an approximate z_max in this way? Is the evolution correction
> (or E-correction) included in the kcorrect package?
>
> Thanks
> Abry
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blanton144_kcorrect_issues_6&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=K1wQRyLId88ghempJcRCpOCPG-yF_rvGkzzLvsJZ0sEdZx1BpO87q5WhjNUT8Vma&s=vxF61Hd_B7ieM9_QfVnEA5zj_hYaD8U5dRsQFigsTUg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAODDFQW44AMJLWDLZIHQOLYAOBPVAVCNFSM6AAAAAA6J7U7FGVHI2DSMVQWIX3LMV43ASLTON2WKOZRHE2TKMZYHA3DANI&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=K1wQRyLId88ghempJcRCpOCPG-yF_rvGkzzLvsJZ0sEdZx1BpO87q5WhjNUT8Vma&s=RNdeORCGNQN02kki7R0__cP8Cbnpk8CyEz52OlsapuU&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 
Michael Blanton, Professor
Department of Physics
New York University

**Comment by Abrygzy** [comment]
> Dear Abry, This *looks* right to me, though of course there might be a bug I'm not seeing. But it does ignore the evolution correction, yes. kcorrect does not include that ... it is a rather model dependent thing. Thanks, Mike
> […](#)
> On Sat, Oct 21, 2023 at 4:27 AM Abry ***@***.***> wrote: Dear Professor Blanton: I am using the kcorrect package to calculate the absolute magnitudes for SDSS galaxies, which is really convenient. I also need to do V-max weighting for the galaxy sample, so I want to use this package to calculate z_max, the maximum redshift that one galaxy can observe. According to my understanding, I can achieve this by putting galaxies to the flux limit. Here is my approach: kc = kcorrect.kcorrect.KcorrectSDSS();# Calculate the kcorrect coefficientscoeffs = kc.fit_coeffs_asinh(redshift = gal_zs, mag=sdss_mags, mag_err=sdss_mag_errs, extinction=sdss_exts)# Convert mags into maggies (maggies,ivars) = kcorrect.utils.sdss_asinh_to_maggies(mag=sdss_mags, mag_err=sdss_mag_errs,extinction=sdss_exts)# Calculate absolute magnitudesab_mags = kc.absmag(maggies=maggies, ivar=ivars, redshift=gal_zs, coeffs=coeffs)ab_mags_r = ab_mags[:,2]m_max_r = 17.77 # Flux limitdef minimize_zmax(z): return m_max_r - cosmo.distmod(z).value - kc.kcorrect(redshift=z, coeffs=coeff)[2] - ab_mag_r Then I can get z_max where minimize_zmax(z_max) = 0 for each galaxy. Can I get an approximate z_max in this way? Is the evolution correction (or E-correction) included in the kcorrect package? Thanks Abry — Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blanton144_kcorrect_issues_6&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=K1wQRyLId88ghempJcRCpOCPG-yF_rvGkzzLvsJZ0sEdZx1BpO87q5WhjNUT8Vma&s=vxF61Hd_B7ieM9_QfVnEA5zj_hYaD8U5dRsQFigsTUg&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAODDFQW44AMJLWDLZIHQOLYAOBPVAVCNFSM6AAAAAA6J7U7FGVHI2DSMVQWIX3LMV43ASLTON2WKOZRHE2TKMZYHA3DANI&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=K1wQRyLId88ghempJcRCpOCPG-yF_rvGkzzLvsJZ0sEdZx1BpO87q5WhjNUT8Vma&s=RNdeORCGNQN02kki7R0__cP8Cbnpk8CyEz52OlsapuU&e=> . You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> -- Michael Blanton, Professor Department of Physics New York University

Dear Professor Blanton:

Thank you, I get it.
By the way, thank you so much for developing this wonderful package! This is the most convenient way that I could imagine when using photometric data from SDSS.

Thanks
Abry
